version: '3.8'

services:
  cloud-run-app:
    image: node:16-alpine3.12
    container_name: cloud-run-app
    ports:
      - 443:443
    working_dir: /app
    volumes:
      - ./:/app
    command:
      - /bin/sh
      - -c
      - |
        npm i
        npm run dev